name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Build and test
        run: mvn -B -ntp clean verify

      - name: Package
        run: mvn -B -ntp -DskipTests package

      - name: Upload jar artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-processing-application-jar
          path: target/*.jar
